name: CI
run-name: ${{ github.actor }} is running cypress on github actions! 🌳
on: [push]
jobs:
  Run-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
        with:
          node-version: "16"
      - uses: cypress-io/github-action@v4.2.0
        with:
          start: npm start
